# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src

# Install Node.js
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

# Install EF Core CLI
RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy solution and projects
COPY FinancePlanner.sln .
COPY FinancePlanner/FinancePlanner.csproj FinancePlanner/
COPY FinancePlannerTests/FinancePlannerTests.csproj FinancePlannerTests/

# Restore
RUN dotnet restore FinancePlanner.sln

# Copy everything
COPY . .

# Install frontend deps
RUN cd FinancePlanner/Frontend && npm install

ENTRYPOINT ["dotnet", "watch", "run", "--project", "FinancePlanner/FinancePlanner.csproj", "--urls=http://0.0.0.0:5000"]
